x <- seq(-3, 3, length.out=301)
lim <- -0.75
pdf("pic_dens_cdf.pdf", width=10, height=6)
par(mfrow=c(1,2))
plot(x, dnorm(x), type="l", ylab="", xlab="", main="Dichtefunktion", ylim=c(0,1))
px <- c(x[1], x[1], x[x<lim], lim, lim)
py <- c(0, dnorm(x[1]), dnorm(x[x<lim]), dnorm(lim), 0)
polygon(px, py, col="green")
text(0, dnorm(0), pos=3, "f(x)")
pos <- min(x)+0.85*(lim-min(x))
text(pos, 0.5*dnorm(pos), "F(b)")
text(lim, 0.0, "b", pos=4)
plot(x, pnorm(x), type="l", ylab="", xlab="", main="Verteilungsfunktion", ylim=c(0,1))
lines(c(lim, lim), c(0, pnorm(lim)))
text(0, pnorm(0), "F(x)", adj=c(0.75,-1.5))
pos <- min(x)+0.85*(lim-min(x))
text(lim, pnorm(lim), "F(b)", adj=c(0.75,-1.5))
text(lim, 0.0, "b", pos=4)
dev.off()